spring:
  application:
    name: ${PROJECT_NAME:soa_lab1}
  profiles:
    active: ${SPRING_PROFILE_NAME:local}
  datasource:
    url: jdbc:postgresql://localhost:5432/flats
    username: example
    password: example
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: create-drop  # или update для продакшена
      show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    com.yourpackage: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

api:
  auth:
    users: ${APP_AUTH_USERS:[{"username":"user","password":"test","roles":["api_user"]}]}